import mongoose from 'mongoose';

const productStoreSchema = new mongoose.Schema({
  item_code:{ type: String, required: true },
  TUT1  :  { type: Number, default: 0 }, 
  TUT2  :  { type: Number, default: 0 }, 
  TYI1  :  { type: Number, default: 0 }, 
  VKM1  :  { type: Number, default: 0 }, 
  PDI1  :  { type: Number, default: 0 }, 
  RPM1  :  { type: Number, default: 0 }, 
  SDI1  :  { type: Number, default: 0 }, 
  TKS1  :  { type: Number, default: 0 }, 
  VNR1  :  { type: Number, default: 0 }, 
  MDU1  :  { type: Number, default: 0 }, 
  SLM1  :  { type: Number, default: 0 }, 
  TRN1  :  { type: Number, default: 0 }, 
  TVL1  :  { type: Number, default: 0 }, 
  APK1  :  { type: Number, default: 0 }, 
  WHTU  :  { type: Number, default: 0 }, 
  HO01  :  { type: Number, default: 0 }, 
  STU1  :  { type: Number, default: 0 }, 
  ASM1  :  { type: Number, default: 0 }, 
  CBE1  :  { type: Number, default: 0 }, 
  CBE2  :  { type: Number, default: 0 }, 
  DGL2  :  { type: Number, default: 0 }, 
  ERL1  :  { type: Number, default: 0 }, 
  KVT1  :  { type: Number, default: 0 }, 
  MAR1  :  { type: Number, default: 0 }, 
  MDU2  :  { type: Number, default: 0 }, 
  MDU3  :  { type: Number, default: 0 }, 
  MDU4  :  { type: Number, default: 0 }, 
  NGR1  :  { type: Number, default: 0 }, 
  PDI2  :  { type: Number, default: 0 }, 
  SLM2  :  { type: Number, default: 0 }, 
  SNL1  :  { type: Number, default: 0 }, 
  STU2  :  { type: Number, default: 0 }, 
  SVK1  :  { type: Number, default: 0 }, 
  SVK2  :  { type: Number, default: 0 }, 
  TPR1  :  { type: Number, default: 0 }, 
  TVL2  :  { type: Number, default: 0 }, 
  VLY1  :  { type: Number, default: 0 }, 
  WHSD  :  { type: Number, default: 0 }, 
  MDWH  :  { type: Number, default: 0 }, 
}, { strict: false });

export default mongoose.models.ProductStore || mongoose.model('ProductStore', productStoreSchema);
